USE LOCADORA;
GO

--GATILHOS PARA ATUALIZAR A TABELA AUDITORIA
CREATE TRIGGER TR_AUDITORIA_USUARIO_0 ON Acesso_Usuario FOR INSERT AS
	INSERT INTO AUDITORIA SELECT
	(SELECT USUARIOATIVO.NOME FROM USUARIOATIVO),
	'CADASTRO',
	'Acesso_Usuario',
	GETDATE(),
	(SELECT USUARIOATIVO.COD FROM USUARIOATIVO)
	FROM inserted
;
--DROP TRIGGER TR_AUDITORIA_USUARIO_0;
GO

CREATE TRIGGER TR_AUDITORIA_USUARIO_1 ON Acesso_Usuario FOR UPDATE AS
	INSERT INTO AUDITORIA SELECT
	(SELECT USUARIOATIVO.NOME FROM USUARIOATIVO),
	'ALTERAÇÃO',
	'Acesso_Usuario',
	GETDATE(),
	(SELECT USUARIOATIVO.COD FROM USUARIOATIVO)
	FROM inserted
;
--DROP TRIGGER TR_AUDITORIA_USUARIO_1;
GO

CREATE TRIGGER TR_AUDITORIA_USUARIO_2 ON Acesso_Usuario FOR DELETE AS
	INSERT INTO AUDITORIA SELECT
	(SELECT USUARIOATIVO.NOME FROM USUARIOATIVO),
	'EXCLUSÃO',
	'Acesso_Usuario',
	GETDATE(),
	(SELECT USUARIOATIVO.COD FROM USUARIOATIVO)
	FROM deleted
;
GO

CREATE TRIGGER TR_AUDITORIA_CLIENTE_0 ON CLIENTE FOR INSERT AS
	INSERT INTO AUDITORIA SELECT
	(SELECT USUARIOATIVO.NOME FROM USUARIOATIVO),
	'CADASTRO',
	'CLIENTE',
	GETDATE(),
	(SELECT USUARIOATIVO.COD FROM USUARIOATIVO)
	FROM inserted
;
--DROP TRIGGER TR_AUDITORIA_CLIENTE_0;
GO

CREATE TRIGGER TR_AUDITORIA_CLIENTE_1 ON CLIENTE FOR UPDATE AS
	INSERT INTO AUDITORIA SELECT
	(SELECT USUARIOATIVO.NOME FROM USUARIOATIVO),
	'ALTERAÇÃO',
	'CLIENTE',
	GETDATE(),
	(SELECT USUARIOATIVO.COD FROM USUARIOATIVO)
	FROM inserted
;
--DROP TRIGGER TR_AUDITORIA_CLIENTE_1;
GO

CREATE TRIGGER TR_AUDITORIA_CLIENTE_2 ON CLIENTE FOR DELETE AS
	INSERT INTO AUDITORIA SELECT
	(SELECT USUARIOATIVO.NOME FROM USUARIOATIVO),
	'EXCLUSÃO',
	'CLIENTE',
	GETDATE(),
	(SELECT USUARIOATIVO.COD FROM USUARIOATIVO)
	FROM deleted
;
--DROP TRIGGER TR_AUDITORIA_CLIENTE_2;
GO

CREATE TRIGGER TR_AUDITORIA_FILMES_0 ON FILMES FOR INSERT AS
	INSERT INTO AUDITORIA SELECT
	(SELECT USUARIOATIVO.NOME FROM USUARIOATIVO),
	'CADASTRO',
	'FILMES',
	GETDATE(),
	(SELECT USUARIOATIVO.COD FROM USUARIOATIVO)
	FROM inserted
;
--DROP TRIGGER TR_AUDITORIA_FILMES_0;
GO

CREATE TRIGGER TR_AUDITORIA_FILMES_1 ON FILMES FOR UPDATE AS
	INSERT INTO AUDITORIA SELECT
	(SELECT USUARIOATIVO.NOME FROM USUARIOATIVO),
	'ALTERAÇÃO',
	'FILMES',
	GETDATE(),
	(SELECT USUARIOATIVO.COD FROM USUARIOATIVO)
	FROM inserted
;
--DROP TRIGGER TR_AUDITORIA_FILMES_1;
GO

CREATE TRIGGER TR_AUDITORIA_FILMES_2 ON FILMES FOR DELETE AS
	INSERT INTO AUDITORIA SELECT
	(SELECT USUARIOATIVO.NOME FROM USUARIOATIVO),
	'EXCLUSÃO',
	'FILMES',
	GETDATE(),
	(SELECT USUARIOATIVO.COD FROM USUARIOATIVO)
	FROM deleted
;
--DROP TRIGGER TR_AUDITORIA_FILMES_2;