use LOCADORA;
GO

-- FUNCAO PARA RETORNAR VALOR DO CREDITO DO CLIENTE
CREATE FUNCTION SF_VALOR_CREC_DEB (@CODIGO VARCHAR) RETURNS MONEY AS
BEGIN
	DECLARE @VAL AS MONEY
	SET @VAL = (SELECT CRED_DEB.VALOR FROM CRED_DEB WHERE CRED_DEB.Codigo_Cli = @CODIGO)
	RETURN @VAL
END
;
GO

--PROCEDIMENTO PARA ATUALIZAR VALORES DA TABELA USUARIO ATIVO
CREATE PROCEDURE SETUSUARIOATIVO @COD VARCHAR(6), @NOME VARCHAR(80) AS
	UPDATE USUARIOATIVO SET COD = @COD
	UPDATE USUARIOATIVO SET NOME = @NOME
;
